In [10]:
!pip install pandas
!pip install openpyxl
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Requirement already satisfied: pandas in c:\users\conta\git-cvc\formation\python\datascience\gitdatascience\.venv\lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in c:\users\conta\git-cvc\formation\python\datascience\gitdatascience\.venv\lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\conta\git-cvc\formation\python\datascience\gitdatascience\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\conta\git-cvc\formation\python\datascience\gitdatascience\.venv\lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in c:\users\conta\git-cvc\formation\python\datascience\gitdatascience\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 23.2.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: openpyxl in c:\users\conta\git-cvc\formation\python\datascience\gitdatascience\.venv\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\conta\git-cvc\formation\python\datascience\gitdatascience\.venv\lib\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 23.2.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
df = pd.read_csv("data/house/house.csv")
df

     loyer  surface
0     1330       37
1     1400       32
2      904       26
3      955       30
4     2545       70
..     ...      ...
540   1490       48
541   2020       58
542   2050       70
543   1220       42
544   1610       44

[545 rows x 2 columns]

In [4]:
df["surface"]

0      37
1      32
2      26
3      30
4      70
       ..
540    48
541    58
542    70
543    42
544    44
Name: surface, Length: 545, dtype: int64

In [7]:
df["loyer_m2"] = df["loyer"] / df["surface"]
df

     loyer  surface   loyer_m2
0     1330       37  35.945946
1     1400       32  43.750000
2      904       26  34.769231
3      955       30  31.833333
4     2545       70  36.357143
..     ...      ...        ...
540   1490       48  31.041667
541   2020       58  34.827586
542   2050       70  29.285714
543   1220       42  29.047619
544   1610       44  36.590909

[545 rows x 3 columns]

In [9]:
df.to_html("data/house/house.html", index=None)

In [11]:
df.to_excel("data/house/house.xlsx", index=None)

In [12]:
df.values

array([[1330.        ,   37.        ,   35.94594595],
       [1400.        ,   32.        ,   43.75      ],
       [ 904.        ,   26.        ,   34.76923077],
       ...,
       [2050.        ,   70.        ,   29.28571429],
       [1220.        ,   42.        ,   29.04761905],
       [1610.        ,   44.        ,   36.59090909]], shape=(545, 3))

In [13]:
df["loyer"].mean()

np.float64(2307.502752293578)

In [14]:
df["loyer"].values.mean()

np.float64(2307.502752293578)