In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
df = pd.read_csv("data/heartdisease/data_with_nan.csv", na_values=".")
# df.dtypes
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,28,1,2,130.0,132.0,0.0,2.0,185.0,0.0,0.0,NaN,NaN,NaN,0
1,29,1,2,120.0,243.0,0.0,0.0,160.0,0.0,0.0,NaN,NaN,NaN,0
2,29,1,2,140.0,NaN,0.0,0.0,170.0,0.0,0.0,NaN,NaN,NaN,0
3,30,0,1,170.0,237.0,0.0,1.0,170.0,0.0,0.0,NaN,NaN,6.0,0
4,31,0,2,100.0,219.0,0.0,1.0,150.0,0.0,0.0,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289,52,1,4,160.0,331.0,0.0,0.0,94.0,1.0,2.5,NaN,NaN,NaN,1
290,54,0,3,130.0,294.0,0.0,1.0,100.0,1.0,0.0,2.0,NaN,NaN,1
291,56,1,4,155.0,342.0,1.0,0.0,150.0,1.0,3.0,2.0,NaN,NaN,1
292,58,0,2,180.0,393.0,0.0,0.0,110.0,1.0,1.0,2.0,NaN,7.0,1
293,65,1,4,130.0,275.0,0.0,1.0,115.0,1.0,1.0,2.0,NaN,NaN,1

In [3]:
df.isnull().sum()

age           0
sex           0
cp            0
trestbps      1
chol         23
fbs           8
restecg       1
thalach       1
exang         1
oldpeak       0
slope       190
ca          291
thal        266
num           0
dtype: int64

In [4]:
# Pour slope, ca & thal droper les colonnes
# Pour chol créer une fonction qui créer mean + std * (rnd - 0.5) * 2 et l'appliquer avec la fonction apply
# .apply(lambda c: chol_mean + chol_std * (np.random.rand() - 0.5) * 2 if pd.isnull(c) else c)
# Pour trestbps, restecg, thalach & exang & fbs droper les lignes avec dropna

In [5]:
df = df.drop(["slope", "ca", "thal"], axis=1)
df

     age  sex  cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  num
0     28    1   2     130.0  132.0  0.0      2.0    185.0    0.0      0.0    0
1     29    1   2     120.0  243.0  0.0      0.0    160.0    0.0      0.0    0
2     29    1   2     140.0    NaN  0.0      0.0    170.0    0.0      0.0    0
3     30    0   1     170.0  237.0  0.0      1.0    170.0    0.0      0.0    0
4     31    0   2     100.0  219.0  0.0      1.0    150.0    0.0      0.0    0
..   ...  ...  ..       ...    ...  ...      ...      ...    ...      ...  ...
289   52    1   4     160.0  331.0  0.0      0.0     94.0    1.0      2.5    1
290   54    0   3     130.0  294.0  0.0      1.0    100.0    1.0      0.0    1
291   56    1   4     155.0  342.0  1.0      0.0    150.0    1.0      3.0    1
292   58    0   2     180.0  393.0  0.0      0.0    110.0    1.0      1.0    1
293   65    1   4     130.0  275.0  0.0      1.0    115.0    1.0      1.0    1

[294 rows x 11 columns]

In [6]:
def chol_replace(c):
    chol_mean + chol_std * (np.random.rand() - 0.5) * 2 if pd.isnull(c) else c

In [7]:
chol_mean = df["chol"].mean()
chol_std = df["chol"].std()
df["chol"] = df["chol"].apply(lambda c: chol_mean + chol_std * (np.random.rand() - 0.5) * 2 if pd.isnull(c) else c)
# df["chol"] = df["chol"].apply(chol_replace)
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,num
0,28,1,2,130.0,132.000000,0.0,2.0,185.0,0.0,0.0,0
1,29,1,2,120.0,243.000000,0.0,0.0,160.0,0.0,0.0,0
2,29,1,2,140.0,213.736987,0.0,0.0,170.0,0.0,0.0,0
3,30,0,1,170.0,237.000000,0.0,1.0,170.0,0.0,0.0,0
4,31,0,2,100.0,219.000000,0.0,1.0,150.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...
289,52,1,4,160.0,331.000000,0.0,0.0,94.0,1.0,2.5,1
290,54,0,3,130.0,294.000000,0.0,1.0,100.0,1.0,0.0,1
291,56,1,4,155.0,342.000000,1.0,0.0,150.0,1.0,3.0,1
292,58,0,2,180.0,393.000000,0.0,0.0,110.0,1.0,1.0,1
293,65,1,4,130.0,275.000000,0.0,1.0,115.0,1.0,1.0,1

In [8]:
df = df.dropna()
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,num
0,28,1,2,130.0,132.000000,0.0,2.0,185.0,0.0,0.0,0
1,29,1,2,120.0,243.000000,0.0,0.0,160.0,0.0,0.0,0
2,29,1,2,140.0,213.736987,0.0,0.0,170.0,0.0,0.0,0
3,30,0,1,170.0,237.000000,0.0,1.0,170.0,0.0,0.0,0
4,31,0,2,100.0,219.000000,0.0,1.0,150.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...
289,52,1,4,160.0,331.000000,0.0,0.0,94.0,1.0,2.5,1
290,54,0,3,130.0,294.000000,0.0,1.0,100.0,1.0,0.0,1
291,56,1,4,155.0,342.000000,1.0,0.0,150.0,1.0,3.0,1
292,58,0,2,180.0,393.000000,0.0,0.0,110.0,1.0,1.0,1
293,65,1,4,130.0,275.000000,0.0,1.0,115.0,1.0,1.0,1

In [9]:
df.to_csv("data/heartdisease/dataclean.csv", index=None)

In [12]:
for row in df.values:
    # for col in row:
    #     print(col)
    print(row)

[ 28.   1.   2. 130. 132.   0.   2. 185.   0.   0.   0.]
[ 29.   1.   2. 120. 243.   0.   0. 160.   0.   0.   0.]
[ 29.           1.           2.         140.         213.73698701
   0.           0.         170.           0.           0.
   0.        ]
[ 30.   0.   1. 170. 237.   0.   1. 170.   0.   0.   0.]
[ 31.   0.   2. 100. 219.   0.   1. 150.   0.   0.   0.]
[ 32.   0.   2. 105. 198.   0.   0. 165.   0.   0.   0.]
[ 32.   1.   2. 110. 225.   0.   0. 184.   0.   0.   0.]
[ 32.   1.   2. 125. 254.   0.   0. 155.   0.   0.   0.]
[ 33.   1.   3. 120. 298.   0.   0. 185.   0.   0.   0.]
[ 34.   0.   2. 130. 161.   0.   0. 190.   0.   0.   0.]
[ 34.   1.   2. 150. 214.   0.   1. 168.   0.   0.   0.]
[ 34.   1.   2.  98. 220.   0.   0. 150.   0.   0.   0.]
[ 35.   0.   1. 120. 160.   0.   1. 185.   0.   0.   0.]
[ 35.   0.   4. 140. 167.   0.   0. 150.   0.   0.   0.]
[ 35.   1.   2. 120. 308.   0.   2. 180.   0.   0.   0.]
[ 35.   1.   2. 150. 264.   0.   0. 168.   0.   0.   0.]
[ 36.   1.   2. 120. 166.   0.   0. 180.   0.   0.   0.]
[ 36.   1.   3. 112. 340.   0.   0. 184.   0.   1.   0.]
[ 36.   1.   3. 130. 209.   0.   0. 178.   0.   0.   0.]
[ 36.   1.   3. 150. 160.   0.   0. 172.   0.   0.   0.]
[ 37.   0.   2. 120. 260.   0.   0. 130.   0.   0.   0.]
[ 37.   0.   3. 130. 211.   0.   0. 142.   0.   0.   0.]
[ 37.   0.   4. 130. 173.   0.   1. 184.   0.   0.   0.]
[ 37.   1.   2. 130. 283.   0.   1.  98.   0.   0.   0.]
[ 37.   1.   3. 130. 194.   0.   0. 150.   0.   0.   0.]
[ 37.   1.   4. 120. 223.   0.   0. 168.   0.   0.   0.]
[ 37.   1.   4. 130. 315.   0.   0. 158.   0.   0.   0.]
[ 38.   1.   2. 140. 297.   0.   0. 150.   0.   0.   0.]
[ 38.   1.   3. 145. 292.   0.   0. 130.   0.   0.   0.]
[ 39.   0.   3. 110. 182.   0.   1. 180.   0.   0.   0.]
[ 39.           1.           2.         120.         306.13953583
   0.           1.         146.           0.           2.
   0.        ]
[ 39.   1.   2. 120. 200.   0.   0. 160.   1.   1.   0.]
[ 39.   1.   2. 120. 204.   0.   0. 145.   0.   0.   0.]
[ 39.           1.           2.         130.         258.80018529
   0.           0.         120.           0.           0.
   0.        ]
[ 39.   1.   2. 190. 241.   0.   0. 106.   0.   0.   0.]
[ 39.   1.   3. 120. 339.   0.   0. 170.   0.   0.   0.]
[ 39.   1.   3. 160. 147.   1.   0. 160.   0.   0.   0.]
[ 39.   1.   4. 110. 273.   0.   0. 132.   0.   0.   0.]
[ 39.   1.   4. 130. 307.   0.   0. 140.   0.   0.   0.]
[ 40.   1.   2. 130. 275.   0.   0. 150.   0.   0.   0.]
[ 40.   1.   2. 140. 289.   0.   0. 172.   0.   0.   0.]
[ 40.   1.   3. 130. 215.   0.   0. 138.   0.   0.   0.]
[ 40.   1.   3. 130. 281.   0.   0. 167.   0.   0.   0.]
[ 40.           1.           3.         140.         270.62285511
   0.           0.         188.           0.           0.
   0.        ]
[ 41.   0.   2. 110. 250.   0.   1. 142.   0.   0.   0.]
[ 41.   0.   2. 125. 184.   0.   0. 180.   0.   0.   0.]
[ 41.   0.   2. 130. 245.   0.   0. 150.   0.   0.   0.]
[ 41.   1.   2. 120. 291.   0.   1. 160.   0.   0.   0.]
[ 41.   1.   2. 120. 295.   0.   0. 170.   0.   0.   0.]
[ 41.   1.   2. 125. 269.   0.   0. 144.   0.   0.   0.]
[ 41.   1.   4. 112. 250.   0.   0. 142.   0.   0.   0.]
[ 42.   0.   3. 115. 211.   0.   1. 137.   0.   0.   0.]
[ 42.   1.   2. 120. 196.   0.   0. 150.   0.   0.   0.]
[ 42.   1.   2. 120. 198.   0.   0. 155.   0.   0.   0.]
[ 42.   1.   2. 150. 268.   0.   0. 136.   0.   0.   0.]
[ 42.    1.    3.  120.  228.    0.    0.  152.    1.    1.5   0. ]
[ 42.   1.   3. 160. 147.   0.   0. 146.   0.   0.   0.]
[ 42.   1.   4. 140. 358.   0.   0. 170.   0.   0.   0.]
[ 43.   0.   1. 100. 223.   0.   0. 142.   0.   0.   0.]
[ 43.   0.   2. 120. 201.   0.   0. 165.   0.   0.   0.]
[ 43.   0.   2. 120. 215.   0.   1. 175.   0.   0.   0.]
[ 43.   0.   2. 120. 249.   0.   1. 176.   0.   0.   0.]
[ 43.   0.   2. 120. 266.   0.   0. 118.   0.   0.   0.]
[ 43.   0.   2. 150. 186.   0.   0. 154.   0.   0.   0.]
[ 43.           0.           3.         150.         224.48603438
   0.           0.         175.           0.           0.
   0.        ]
[ 43.   1.   2. 142. 207.   0.   0. 138.   0.   0.   0.]
[ 44.   0.   4. 120. 218.   0.   1. 115.   0.   0.   0.]
[ 44.   1.   2. 120. 184.   0.   0. 142.   0.   1.   0.]
[ 44.   1.   2. 130. 215.   0.   0. 135.   0.   0.   0.]
[ 44.   1.   4. 150. 412.   0.   0. 170.   0.   0.   0.]
[ 45.   0.   2. 130. 237.   0.   0. 170.   0.   0.   0.]
[ 45.           0.           2.         180.         203.80398664
   0.           0.         180.           0.           0.
   0.        ]
[ 45.   0.   4. 132. 297.   0.   0. 144.   0.   0.   0.]
[ 45.   1.   2. 140. 224.   1.   0. 122.   0.   0.   0.]
[ 45.           1.           3.         135.         255.03866178
   0.           0.         110.           0.           0.
   0.        ]
[ 45.   1.   4. 120. 225.   0.   0. 140.   0.   0.   0.]
[ 45.   1.   4. 140. 224.   0.   0. 144.   0.   0.   0.]
[ 46.   0.   4. 130. 238.   0.   0.  90.   0.   0.   0.]
[ 46.   1.   2. 140. 275.   0.   0. 165.   1.   0.   0.]
[ 46.   1.   3. 120. 230.   0.   0. 150.   0.   0.   0.]
[ 46.   1.   4. 110. 238.   0.   1. 140.   1.   1.   0.]
[ 46.   1.   4. 110. 240.   0.   1. 140.   0.   0.   0.]
[ 46.   1.   4. 180. 280.   0.   1. 120.   0.   0.   0.]
[ 47.   0.   2. 140. 257.   0.   0. 135.   0.   1.   0.]
[ 47.           0.           3.         130.         285.32703997
   0.           0.         145.           0.           2.
   0.        ]
[ 47.   1.   1. 110. 249.   0.   0. 150.   0.   0.   0.]
[ 47.   1.   2. 160. 263.   0.   0. 174.   0.   0.   0.]
[ 47.   1.   4. 140. 276.   1.   0. 125.   1.   0.   0.]
[ 48.           0.           2.         120.         316.38579904
   1.           1.         148.           0.           0.
   0.        ]
[ 48.   0.   2. 120. 284.   0.   0. 120.   0.   0.   0.]
[ 48.   0.   3. 120. 195.   0.   0. 125.   0.   0.   0.]
[ 48.   0.   4. 108. 163.   0.   0. 175.   0.   2.   0.]
[ 48.   0.   4. 120. 254.   0.   1. 110.   0.   0.   0.]
[ 48.   0.   4. 150. 227.   0.   0. 130.   1.   1.   0.]
[ 48.           1.           2.         100.         218.68116145
   0.           0.         100.           0.           0.
   0.        ]
[ 48.   1.   2. 130. 245.   0.   0. 160.   0.   0.   0.]
[ 48.   1.   2. 140. 238.   0.   0. 118.   0.   0.   0.]
[ 48.   1.   3. 110. 211.   0.   0. 138.   0.   0.   0.]
[ 49.           0.           2.         110.         202.25927564
   0.           0.         160.           0.           0.
   0.        ]
[ 49.           0.           2.         110.         228.88356668
   0.           0.         160.           0.           0.
   0.        ]
[ 49.   0.   2. 124. 201.   0.   0. 164.   0.   0.   0.]
[ 49.   0.   3. 130. 207.   0.   1. 135.   0.   0.   0.]
[ 49.   1.   2. 100. 253.   0.   0. 174.   0.   0.   0.]
[ 49.   1.   3. 140. 187.   0.   0. 172.   0.   0.   0.]
[ 49.           1.           4.         140.         256.57309069
   0.           0.         130.           0.           0.
   0.        ]
[ 50.   0.   2. 110. 202.   0.   0. 145.   0.   0.   0.]
[ 50.   0.   4. 120. 328.   0.   0. 110.   1.   1.   0.]
[ 50.   1.   2. 120. 168.   0.   0. 160.   0.   0.   0.]
[ 50.   1.   2. 140. 216.   0.   0. 170.   0.   0.   0.]
[ 50.   1.   2. 170. 209.   0.   1. 116.   0.   0.   0.]
[ 50.   1.   4. 140. 129.   0.   0. 135.   0.   0.   0.]
[ 50.   1.   4. 150. 215.   0.   0. 140.   1.   0.   0.]
[ 51.   0.   2. 160. 194.   0.   0. 170.   0.   0.   0.]
[ 51.   0.   3. 110. 190.   0.   0. 120.   0.   0.   0.]
[ 51.   0.   3. 130. 220.   0.   0. 160.   1.   2.   0.]
[ 51.    0.    3.  150.  200.    0.    0.  120.    0.    0.5   0. ]
[ 51.   1.   2. 125. 188.   0.   0. 145.   0.   0.   0.]
[ 51.   1.   2. 130. 224.   0.   0. 150.   0.   0.   0.]
[ 51.   1.   4. 130. 179.   0.   0. 100.   0.   0.   0.]
[ 52.   0.   2. 120. 210.   0.   0. 148.   0.   0.   0.]
[ 52.           0.           2.         140.         184.67765548
   0.           0.         140.           0.           0.
   0.        ]
[ 52.   0.   3. 125. 272.   0.   0. 139.   0.   0.   0.]
[ 52.    0.    4.  130.  180.    0.    0.  140.    1.    1.5   0. ]
[ 52.   1.   2. 120. 284.   0.   0. 118.   0.   0.   0.]
[ 52.   1.   2. 140. 100.   0.   0. 138.   1.   0.   0.]
[ 52.   1.   2. 160. 196.   0.   0. 165.   0.   0.   0.]
[ 52.   1.   3. 140. 259.   0.   1. 170.   0.   0.   0.]
[ 53.   0.   2. 140. 216.   0.   0. 142.   1.   2.   0.]
[ 53.   0.   3. 120. 274.   0.   0. 130.   0.   0.   0.]
[ 53.           1.           2.         120.         184.06034413
   0.           0.         132.           0.           0.
   0.        ]
[ 53.   1.   2. 140. 320.   0.   0. 162.   0.   0.   0.]
[ 53.   1.   3. 120. 195.   0.   0. 140.   0.   0.   0.]
[ 53.   1.   4. 124. 260.   0.   1. 112.   1.   3.   0.]
[ 53.   1.   4. 130. 182.   0.   0. 148.   0.   0.   0.]
[ 53.   1.   4. 140. 243.   0.   0. 155.   0.   0.   0.]
[ 54.   0.   2. 120. 221.   0.   0. 138.   0.   1.   0.]
[ 54.   0.   2. 120. 230.   1.   0. 140.   0.   0.   0.]
[ 54.    0.    2.  120.  273.    0.    0.  150.    0.    1.5   0. ]
[ 54.   0.   2. 130. 253.   0.   1. 155.   0.   0.   0.]
[ 54.   0.   2. 150. 230.   0.   0. 130.   0.   0.   0.]
[ 54.   0.   2. 160. 312.   0.   0. 130.   0.   0.   0.]
[ 54.   1.   1. 120. 171.   0.   0. 137.   0.   2.   0.]
[ 54.   1.   2. 110. 208.   0.   0. 142.   0.   0.   0.]
[ 54.   1.   2. 120. 238.   0.   0. 154.   0.   0.   0.]
[ 54.   1.   2. 120. 246.   0.   0. 110.   0.   0.   0.]
[ 54.   1.   2. 160. 195.   0.   1. 130.   0.   1.   0.]
[ 54.   1.   2. 160. 305.   0.   0. 175.   0.   0.   0.]
[ 54.   1.   3. 120. 217.   0.   0. 137.   0.   0.   0.]
[ 54.           1.           3.         150.         274.94753654
   0.           0.         122.           0.           0.
   0.        ]
[ 54.   1.   4. 150. 365.   0.   1. 134.   0.   1.   0.]
[ 55.   0.   2. 110. 344.   0.   1. 160.   0.   0.   0.]
[ 55.   0.   2. 122. 320.   0.   0. 155.   0.   0.   0.]
[ 55.   0.   2. 130. 394.   0.   2. 150.   0.   0.   0.]
[ 55.   1.   2. 120. 256.   1.   0. 137.   0.   0.   0.]
[ 55.   1.   2. 140. 196.   0.   0. 150.   0.   0.   0.]
[ 55.   1.   2. 145. 326.   0.   0. 155.   0.   0.   0.]
[ 55.   1.   3. 110. 277.   0.   0. 160.   0.   0.   0.]
[ 55.   1.   3. 120. 220.   0.   2. 134.   0.   0.   0.]
[ 55.   1.   4. 120. 270.   0.   0. 140.   0.   0.   0.]
[ 55.    1.    4.  140.  229.    0.    0.  110.    1.    0.5   0. ]
[ 56.   1.   2. 130. 184.   0.   0. 100.   0.   0.   0.]
[ 56.           1.           3.         130.         195.05197292
   0.           0.         114.           0.           0.
   0.        ]
[ 56.   1.   3. 130. 276.   0.   0. 128.   1.   1.   0.]
[ 56.   1.   4. 120.  85.   0.   0. 140.   0.   0.   0.]
[ 57.   0.   1. 130. 308.   0.   0.  98.   0.   1.   0.]
[ 57.    0.    4.  180.  347.    0.    1.  126.    1.    0.8   0. ]
[ 57.   1.   2. 140. 260.   1.   0. 140.   0.   0.   0.]
[ 58.   1.   2. 130. 230.   0.   0. 150.   0.   0.   0.]
[ 58.   1.   2. 130. 251.   0.   0. 110.   0.   0.   0.]
[ 58.   1.   3. 140. 179.   0.   0. 160.   0.   0.   0.]
[ 58.   1.   4. 135. 222.   0.   0. 100.   0.   0.   0.]
[ 59.   0.   2. 130. 188.   0.   0. 124.   0.   1.   0.]
[ 59.   1.   2. 140. 287.   0.   0. 150.   0.   0.   0.]
[ 59.   1.   3. 130. 318.   0.   0. 120.   1.   1.   0.]
[ 59.   1.   3. 180. 213.   0.   0. 100.   0.   0.   0.]
[ 59.           1.           4.         140.         289.65352239
   0.           0.         140.           0.           0.
   0.        ]
[ 60.   1.   3. 120. 246.   0.   2. 135.   0.   0.   0.]
[ 61.   0.   4. 130. 294.   0.   1. 120.   1.   1.   0.]
[ 61.   1.   4. 125. 292.   0.   1. 115.   1.   0.   0.]
[ 62.   0.   1. 160. 193.   0.   0. 116.   0.   0.   0.]
[ 62.   1.   2. 140. 271.   0.   0. 152.   0.   1.   0.]
[ 31.    1.    4.  120.  270.    0.    0.  153.    1.    1.5   1. ]
[ 33.   0.   4. 100. 246.   0.   0. 150.   1.   1.   1.]
[ 34.   1.   1. 140. 156.   0.   0. 180.   0.   0.   1.]
[ 35.   1.   2. 110. 257.   0.   0. 140.   0.   0.   1.]
[ 36.   1.   2. 120. 267.   0.   0. 160.   0.   3.   1.]
[ 37.    1.    4.  140.  207.    0.    0.  130.    1.    1.5   1. ]
[ 38.   1.   4. 110. 196.   0.   0. 166.   0.   0.   1.]
[ 38.   1.   4. 120. 282.   0.   0. 170.   0.   0.   1.]
[ 38.    1.    4.   92.  117.    0.    0.  134.    1.    2.5   1. ]
[ 41.   1.   4. 110. 289.   0.   0. 170.   0.   0.   1.]
[ 43.   1.   4. 150. 247.   0.   0. 130.   1.   2.   1.]
[ 46.   1.   4. 110. 202.   0.   0. 150.   1.   0.   1.]
[ 46.   1.   4. 118. 186.   0.   0. 124.   0.   0.   1.]
[ 46.   1.   4. 120. 277.   0.   0. 125.   1.   1.   1.]
[ 47.   1.   3. 140. 193.   0.   0. 145.   1.   1.   1.]
[ 47.    1.    4.  150.  226.    0.    0.   98.    1.    1.5   1. ]
[ 48.   1.   4. 106. 263.   1.   0. 110.   0.   0.   1.]
[ 48.   1.   4. 120. 260.   0.   0. 115.   0.   2.   1.]
[ 48.   1.   4. 160. 268.   0.   0. 103.   1.   1.   1.]
[ 49.   0.   3. 160. 180.   0.   0. 156.   0.   1.   1.]
[ 49.   1.   3. 115. 265.   0.   0. 175.   0.   0.   1.]
[ 49.   1.   4. 130. 206.   0.   0. 170.   0.   0.   1.]
[ 50.   0.   3. 140. 288.   0.   0. 140.   1.   0.   1.]
[ 50.   1.   4. 145. 264.   0.   0. 150.   0.   0.   1.]
[ 51.   0.   4. 160. 303.   0.   0. 150.   1.   1.   1.]
[ 52.   1.   4. 130. 225.   0.   0. 120.   1.   2.   1.]
[ 54.   1.   4. 125. 216.   0.   0. 140.   0.   0.   1.]
[ 54.   1.   4. 125. 224.   0.   0. 122.   0.   2.   1.]
[ 55.   1.   4. 140. 201.   0.   0. 130.   1.   3.   1.]
[ 57.   1.   2. 140. 265.   0.   1. 145.   1.   1.   1.]
[ 58.   1.   3. 130. 213.   0.   1. 140.   0.   0.   1.]
[ 59.    0.    4.  130.  338.    1.    1.  130.    1.    1.5   1. ]
[ 60.   1.   4. 100. 248.   0.   0. 125.   0.   1.   1.]
[ 63.   1.   4. 150. 223.   0.   0. 115.   0.   0.   1.]
[ 65.    1.    4.  140.  306.    1.    0.   87.    1.    1.5   1. ]
[ 32.   1.   4. 118. 529.   0.   0. 130.   0.   0.   1.]
[ 38.           1.           4.         110.         250.62745608
   0.           0.         150.           1.           1.
   1.        ]
[ 39.   1.   4. 110. 280.   0.   0. 150.   0.   0.   1.]
[ 40.   0.   4. 150. 392.   0.   0. 130.   0.   2.   1.]
[ 43.   1.   1. 120. 291.   0.   1. 155.   0.   0.   1.]
[ 45.   1.   4. 130. 219.   0.   1. 130.   1.   1.   1.]
[ 46.   1.   4. 120. 231.   0.   0. 115.   1.   0.   1.]
[ 46.   1.   4. 130. 222.   0.   0. 112.   0.   0.   1.]
[ 48.   1.   4. 122. 275.   1.   1. 150.   1.   2.   1.]
[ 48.   1.   4. 160. 193.   0.   0. 102.   1.   3.   1.]
[ 48.    1.    4.  160.  329.    0.    0.   92.    1.    1.5   1. ]
[ 48.   1.   4. 160. 355.   0.   0.  99.   1.   2.   1.]
[ 50.   1.   4. 130. 233.   0.   0. 121.   1.   2.   1.]
[ 52.   1.   4. 120. 182.   0.   0. 150.   0.   0.   1.]
[ 52.           1.           4.         170.         289.09796301
   0.           0.         126.           1.           1.5
   1.        ]
[ 53.   1.   4. 120. 246.   0.   0. 116.   1.   0.   1.]
[ 54.    1.    3.  120.  237.    0.    0.  150.    1.    1.5   1. ]
[ 54.   1.   4. 130. 242.   0.   0.  91.   1.   1.   1.]
[ 54.   1.   4. 130. 603.   1.   0. 125.   1.   1.   1.]
[ 54.           1.           4.         140.         303.36776766
   0.           0.         118.           1.           0.
   1.        ]
[ 54.   1.   4. 200. 198.   0.   0. 142.   1.   2.   1.]
[ 55.    1.    4.  140.  268.    0.    0.  128.    1.    1.5   1. ]
[ 56.   1.   4. 150. 213.   1.   0. 125.   1.   1.   1.]
[ 57.   1.   4. 150. 255.   0.   0.  92.   1.   3.   1.]
[ 58.   1.   3. 160. 211.   1.   1.  92.   0.   0.   1.]
[ 58.   1.   4. 130. 263.   0.   0. 140.   1.   2.   1.]
[ 41.   1.   4. 130. 172.   0.   1. 130.   0.   2.   1.]
[ 43.   1.   4. 120. 175.   0.   0. 120.   1.   1.   1.]
[ 44.   1.   2. 150. 288.   0.   0. 150.   1.   3.   1.]
[ 44.   1.   4. 130. 290.   0.   0. 100.   1.   2.   1.]
[ 46.   1.   1. 140. 272.   1.   0. 175.   0.   2.   1.]
[ 47.   0.   3. 135. 248.   1.   0. 170.   0.   0.   1.]
[ 48.    0.    4.  138.  214.    0.    0.  108.    1.    1.5   1. ]
[ 49.   1.   4. 130. 341.   0.   0. 120.   1.   1.   1.]
[ 49.   1.   4. 140. 234.   0.   0. 140.   1.   1.   1.]
[ 51.   1.   3. 135. 160.   0.   0. 150.   0.   2.   1.]
[ 52.   1.   4. 112. 342.   0.   1.  96.   1.   1.   1.]
[ 52.   1.   4. 130. 298.   0.   0. 110.   1.   1.   1.]
[ 52.   1.   4. 140. 404.   0.   0. 124.   1.   2.   1.]
[ 52.   1.   4. 160. 246.   0.   1.  82.   1.   4.   1.]
[ 53.   1.   3. 145. 518.   0.   0. 130.   0.   0.   1.]
[ 53.    1.    4.  180.  285.    0.    1.  120.    1.    1.5   1. ]
[ 54.    1.    4.  140.  216.    0.    0.  105.    0.    1.5   1. ]
[ 55.   1.   2. 160. 292.   1.   0. 143.   1.   2.   1.]
[ 55.   1.   4. 145. 248.   0.   0.  96.   1.   2.   1.]
[ 56.   0.   2. 120. 279.   0.   0. 150.   0.   1.   1.]
[ 56.    1.    4.  150.  230.    0.    1.  124.    1.    1.5   1. ]
[ 56.   1.   4. 170. 388.   0.   1. 122.   1.   2.   1.]
[ 58.   1.   2. 136. 164.   0.   1.  99.   1.   2.   1.]
[ 59.          1.          4.        130.        201.7840737   0.
   0.        125.          0.          0.          1.       ]
[ 59.   1.   4. 140. 264.   1.   2. 119.   1.   0.   1.]
[ 65.   1.   4. 170. 263.   1.   0. 112.   1.   2.   1.]
[ 66.          1.          4.        140.        256.1665233   0.
   0.         94.          1.          1.          1.       ]
[ 41.   1.   4. 120. 336.   0.   0. 118.   1.   3.   1.]
[ 43.   1.   4. 140. 288.   0.   0. 135.   1.   2.   1.]
[ 44.   1.   4. 135. 491.   0.   0. 135.   0.   0.   1.]
[ 47.   0.   4. 120. 205.   0.   0.  98.   1.   2.   1.]
[ 47.   1.   4. 160. 291.   0.   1. 158.   1.   3.   1.]
[ 49.   1.   4. 128. 212.   0.   0.  96.   1.   0.   1.]
[ 49.   1.   4. 150. 222.   0.   0. 122.   0.   2.   1.]
[ 50.   1.   4. 140. 231.   0.   1. 140.   1.   5.   1.]
[ 50.    1.    4.  140.  341.    0.    1.  125.    1.    2.5   1. ]
[ 52.   1.   4. 140. 266.   0.   0. 134.   1.   2.   1.]
[ 52.    1.    4.  160.  331.    0.    0.   94.    1.    2.5   1. ]
[ 54.   0.   3. 130. 294.   0.   1. 100.   1.   0.   1.]
[ 56.   1.   4. 155. 342.   1.   0. 150.   1.   3.   1.]
[ 58.   0.   2. 180. 393.   0.   0. 110.   1.   1.   1.]
[ 65.   1.   4. 130. 275.   0.   1. 115.   1.   1.   1.]

In [15]:
for index, row in df.iterrows():
    for col in row:
        print(col)

28.0
1.0
2.0
130.0
132.0
0.0
2.0
185.0
0.0
0.0
0.0
29.0
1.0
2.0
120.0
243.0
0.0
0.0
160.0
0.0
0.0
0.0
29.0
1.0
2.0
140.0
213.73698701383432
0.0
0.0
170.0
0.0
0.0
0.0
30.0
0.0
1.0
170.0
237.0
0.0
1.0
170.0
0.0
0.0
0.0
31.0
0.0
2.0
100.0
219.0
0.0
1.0
150.0
0.0
0.0
0.0
32.0
0.0
2.0
105.0
198.0
0.0
0.0
165.0
0.0
0.0
0.0
32.0
1.0
2.0
110.0
225.0
0.0
0.0
184.0
0.0
0.0
0.0
32.0
1.0
2.0
125.0
254.0
0.0
0.0
155.0
0.0
0.0
0.0
33.0
1.0
3.0
120.0
298.0
0.0
0.0
185.0
0.0
0.0
0.0
34.0
0.0
2.0
130.0
161.0
0.0
0.0
190.0
0.0
0.0
0.0
34.0
1.0
2.0
150.0
214.0
0.0
1.0
168.0
0.0
0.0
0.0
34.0
1.0
2.0
98.0
220.0
0.0
0.0
150.0
0.0
0.0
0.0
35.0
0.0
1.0
120.0
160.0
0.0
1.0
185.0
0.0
0.0
0.0
35.0
0.0
4.0
140.0
167.0
0.0
0.0
150.0
0.0
0.0
0.0
35.0
1.0
2.0
120.0
308.0
0.0
2.0
180.0
0.0
0.0
0.0
35.0
1.0
2.0
150.0
264.0
0.0
0.0
168.0
0.0
0.0
0.0
36.0
1.0
2.0
120.0
166.0
0.0
0.0
180.0
0.0
0.0
0.0
36.0
1.0
3.0
112.0
340.0
0.0
0.0
184.0
0.0
1.0
0.0
36.0
1.0
3.0
130.0
209.0
0.0
0.0
178.0
0.0
0.0
0.0
36.0
1.0
3.0
150.0
160.0
0.0
0.0
172.0
0.0
0.0
0.0
37.0
0.0
2.0
120.0
260.0
0.0
0.0
130.0
0.0
0.0
0.0
37.0
0.0
3.0
130.0
211.0
0.0
0.0
142.0
0.0
0.0
0.0
37.0
0.0
4.0
130.0
173.0
0.0
1.0
184.0
0.0
0.0
0.0
37.0
1.0
2.0
130.0
283.0
0.0
1.0
98.0
0.0
0.0
0.0
37.0
1.0
3.0
130.0
194.0
0.0
0.0
150.0
0.0
0.0
0.0
37.0
1.0
4.0
120.0
223.0
0.0
0.0
168.0
0.0
0.0
0.0
37.0
1.0
4.0
130.0
315.0
0.0
0.0
158.0
0.0
0.0
0.0
38.0
1.0
2.0
140.0
297.0
0.0
0.0
150.0
0.0
0.0
0.0
38.0
1.0
3.0
145.0
292.0
0.0
0.0
130.0
0.0
0.0
0.0
39.0
0.0
3.0
110.0
182.0
0.0
1.0
180.0
0.0
0.0
0.0
39.0
1.0
2.0
120.0
306.13953583282705
0.0
1.0
146.0
0.0
2.0
0.0
39.0
1.0
2.0
120.0
200.0
0.0
0.0
160.0
1.0
1.0
0.0
39.0
1.0
2.0
120.0
204.0
0.0
0.0
145.0
0.0
0.0
0.0
39.0
1.0
2.0
130.0
258.8001852922438
0.0
0.0
120.0
0.0
0.0
0.0
39.0
1.0
2.0
190.0
241.0
0.0
0.0
106.0
0.0
0.0
0.0
39.0
1.0
3.0
120.0
339.0
0.0
0.0
170.0
0.0
0.0
0.0
39.0
1.0
3.0
160.0
147.0
1.0
0.0
160.0
0.0
0.0
0.0
39.0
1.0
4.0
110.0
273.0
0.0
0.0
132.0
0.0
0.0
0.0
39.0
1.0
4.0
130.0
307.0
0.0
0.0
140.0
0.0
0.0
0.0
40.0
1.0
2.0
130.0
275.0
0.0
0.0
150.0
0.0
0.0
0.0
40.0
1.0
2.0
140.0
289.0
0.0
0.0
172.0
0.0
0.0
0.0
40.0
1.0
3.0
130.0
215.0
0.0
0.0
138.0
0.0
0.0
0.0
40.0
1.0
3.0
130.0
281.0
0.0
0.0
167.0
0.0
0.0
0.0
40.0
1.0
3.0
140.0
270.62285511222933
0.0
0.0
188.0
0.0
0.0
0.0
41.0
0.0
2.0
110.0
250.0
0.0
1.0
142.0
0.0
0.0
0.0
41.0
0.0
2.0
125.0
184.0
0.0
0.0
180.0
0.0
0.0
0.0
41.0
0.0
2.0
130.0
245.0
0.0
0.0
150.0
0.0
0.0
0.0
41.0
1.0
2.0
120.0
291.0
0.0
1.0
160.0
0.0
0.0
0.0
41.0
1.0
2.0
120.0
295.0
0.0
0.0
170.0
0.0
0.0
0.0
41.0
1.0
2.0
125.0
269.0
0.0
0.0
144.0
0.0
0.0
0.0
41.0
1.0
4.0
112.0
250.0
0.0
0.0
142.0
0.0
0.0
0.0
42.0
0.0
3.0
115.0
211.0
0.0
1.0
137.0
0.0
0.0
0.0
42.0
1.0
2.0
120.0
196.0
0.0
0.0
150.0
0.0
0.0
0.0
42.0
1.0
2.0
120.0
198.0
0.0
0.0
155.0
0.0
0.0
0.0
42.0
1.0
2.0
150.0
268.0
0.0
0.0
136.0
0.0
0.0
0.0
42.0
1.0
3.0
120.0
228.0
0.0
0.0
152.0
1.0
1.5
0.0
42.0
1.0
3.0
160.0
147.0
0.0
0.0
146.0
0.0
0.0
0.0
42.0
1.0
4.0
140.0
358.0
0.0
0.0
170.0
0.0
0.0
0.0
43.0
0.0
1.0
100.0
223.0
0.0
0.0
142.0
0.0
0.0
0.0
43.0
0.0
2.0
120.0
201.0
0.0
0.0
165.0
0.0
0.0
0.0
43.0
0.0
2.0
120.0
215.0
0.0
1.0
175.0
0.0
0.0
0.0
43.0
0.0
2.0
120.0
249.0
0.0
1.0
176.0
0.0
0.0
0.0
43.0
0.0
2.0
120.0
266.0
0.0
0.0
118.0
0.0
0.0
0.0
43.0
0.0
2.0
150.0
186.0
0.0
0.0
154.0
0.0
0.0
0.0
43.0
0.0
3.0
150.0
224.4860343799459
0.0
0.0
175.0
0.0
0.0
0.0
43.0
1.0
2.0
142.0
207.0
0.0
0.0
138.0
0.0
0.0
0.0
44.0
0.0
4.0
120.0
218.0
0.0
1.0
115.0
0.0
0.0
0.0
44.0
1.0
2.0
120.0
184.0
0.0
0.0
142.0
0.0
1.0
0.0
44.0
1.0
2.0
130.0
215.0
0.0
0.0
135.0
0.0
0.0
0.0
44.0
1.0
4.0
150.0
412.0
0.0
0.0
170.0
0.0
0.0
0.0
45.0
0.0
2.0
130.0
237.0
0.0
0.0
170.0
0.0
0.0
0.0
45.0
0.0
2.0
180.0
203.8039866350615
0.0
0.0
180.0
0.0
0.0
0.0
45.0
0.0
4.0
132.0
297.0
0.0
0.0
144.0
0.0
0.0
0.0
45.0
1.0
2.0
140.0
224.0
1.0
0.0
122.0
0.0
0.0
0.0
45.0
1.0
3.0
135.0
255.03866177661106
0.0
0.0
110.0
0.0
0.0
0.0
45.0
1.0
4.0
120.0
225.0
0.0
0.0
140.0
0.0
0.0
0.0
45.0
1.0
4.0
140.0
224.0
0.0
0.0
144.0
0.0
0.0
0.0
46.0
0.0
4.0
130.0
238.0
0.0
0.0
90.0
0.0
0.0
0.0
46.0
1.0
2.0
140.0
275.0
0.0
0.0
165.0
1.0
0.0
0.0
46.0
1.0
3.0
120.0
230.0
0.0
0.0
150.0
0.0
0.0
0.0
46.0
1.0
4.0
110.0
238.0
0.0
1.0
140.0
1.0
1.0
0.0
46.0
1.0
4.0
110.0
240.0
0.0
1.0
140.0
0.0
0.0
0.0
46.0
1.0
4.0
180.0
280.0
0.0
1.0
120.0
0.0
0.0
0.0
47.0
0.0
2.0
140.0
257.0
0.0
0.0
135.0
0.0
1.0
0.0
47.0
0.0
3.0
130.0
285.32703997465796
0.0
0.0
145.0
0.0
2.0
0.0
47.0
1.0
1.0
110.0
249.0
0.0
0.0
150.0
0.0
0.0
0.0
47.0
1.0
2.0
160.0
263.0
0.0
0.0
174.0
0.0
0.0
0.0
47.0
1.0
4.0
140.0
276.0
1.0
0.0
125.0
1.0
0.0
0.0
48.0
0.0
2.0
120.0
316.38579904084446
1.0
1.0
148.0
0.0
0.0
0.0
48.0
0.0
2.0
120.0
284.0
0.0
0.0
120.0
0.0
0.0
0.0
48.0
0.0
3.0
120.0
195.0
0.0
0.0
125.0
0.0
0.0
0.0
48.0
0.0
4.0
108.0
163.0
0.0
0.0
175.0
0.0
2.0
0.0
48.0
0.0
4.0
120.0
254.0
0.0
1.0
110.0
0.0
0.0
0.0
48.0
0.0
4.0
150.0
227.0
0.0
0.0
130.0
1.0
1.0
0.0
48.0
1.0
2.0
100.0
218.68116144992385
0.0
0.0
100.0
0.0
0.0
0.0
48.0
1.0
2.0
130.0
245.0
0.0
0.0
160.0
0.0
0.0
0.0
48.0
1.0
2.0
140.0
238.0
0.0
0.0
118.0
0.0
0.0
0.0
48.0
1.0
3.0
110.0
211.0
0.0
0.0
138.0
0.0
0.0
0.0
49.0
0.0
2.0
110.0
202.2592756372506
0.0
0.0
160.0
0.0
0.0
0.0
49.0
0.0
2.0
110.0
228.88356668488845
0.0
0.0
160.0
0.0
0.0
0.0
49.0
0.0
2.0
124.0
201.0
0.0
0.0
164.0
0.0
0.0
0.0
49.0
0.0
3.0
130.0
207.0
0.0
1.0
135.0
0.0
0.0
0.0
49.0
1.0
2.0
100.0
253.0
0.0
0.0
174.0
0.0
0.0
0.0
49.0
1.0
3.0
140.0
187.0
0.0
0.0
172.0
0.0
0.0
0.0
49.0
1.0
4.0
140.0
256.5730906940783
0.0
0.0
130.0
0.0
0.0
0.0
50.0
0.0
2.0
110.0
202.0
0.0
0.0
145.0
0.0
0.0
0.0
50.0
0.0
4.0
120.0
328.0
0.0
0.0
110.0
1.0
1.0
0.0
50.0
1.0
2.0
120.0
168.0
0.0
0.0
160.0
0.0
0.0
0.0
50.0
1.0
2.0
140.0
216.0
0.0
0.0
170.0
0.0
0.0
0.0
50.0
1.0
2.0
170.0
209.0
0.0
1.0
116.0
0.0
0.0
0.0
50.0
1.0
4.0
140.0
129.0
0.0
0.0
135.0
0.0
0.0
0.0
50.0
1.0
4.0
150.0
215.0
0.0
0.0
140.0
1.0
0.0
0.0
51.0
0.0
2.0
160.0
194.0
0.0
0.0
170.0
0.0
0.0
0.0
51.0
0.0
3.0
110.0
190.0
0.0
0.0
120.0
0.0
0.0
0.0
51.0
0.0
3.0
130.0
220.0
0.0
0.0
160.0
1.0
2.0
0.0
51.0
0.0
3.0
150.0
200.0
0.0
0.0
120.0
0.0
0.5
0.0
51.0
1.0
2.0
125.0
188.0
0.0
0.0
145.0
0.0
0.0
0.0
51.0
1.0
2.0
130.0
224.0
0.0
0.0
150.0
0.0
0.0
0.0
51.0
1.0
4.0
130.0
179.0
0.0
0.0
100.0
0.0
0.0
0.0
52.0
0.0
2.0
120.0
210.0
0.0
0.0
148.0
0.0
0.0
0.0
52.0
0.0
2.0
140.0
184.67765547512155
0.0
0.0
140.0
0.0
0.0
0.0
52.0
0.0
3.0
125.0
272.0
0.0
0.0
139.0
0.0
0.0
0.0
52.0
0.0
4.0
130.0
180.0
0.0
0.0
140.0
1.0
1.5
0.0
52.0
1.0
2.0
120.0
284.0
0.0
0.0
118.0
0.0
0.0
0.0
52.0
1.0
2.0
140.0
100.0
0.0
0.0
138.0
1.0
0.0
0.0
52.0
1.0
2.0
160.0
196.0
0.0
0.0
165.0
0.0
0.0
0.0
52.0
1.0
3.0
140.0
259.0
0.0
1.0
170.0
0.0
0.0
0.0
53.0
0.0
2.0
140.0
216.0
0.0
0.0
142.0
1.0
2.0
0.0
53.0
0.0
3.0
120.0
274.0
0.0
0.0
130.0
0.0
0.0
0.0
53.0
1.0
2.0
120.0
184.0603441266116
0.0
0.0
132.0
0.0
0.0
0.0
53.0
1.0
2.0
140.0
320.0
0.0
0.0
162.0
0.0
0.0
0.0
53.0
1.0
3.0
120.0
195.0
0.0
0.0
140.0
0.0
0.0
0.0
53.0
1.0
4.0
124.0
260.0
0.0
1.0
112.0
1.0
3.0
0.0
53.0
1.0
4.0
130.0
182.0
0.0
0.0
148.0
0.0
0.0
0.0
53.0
1.0
4.0
140.0
243.0
0.0
0.0
155.0
0.0
0.0
0.0
54.0
0.0
2.0
120.0
221.0
0.0
0.0
138.0
0.0
1.0
0.0
54.0
0.0
2.0
120.0
230.0
1.0
0.0
140.0
0.0
0.0
0.0
54.0
0.0
2.0
120.0
273.0
0.0
0.0
150.0
0.0
1.5
0.0
54.0
0.0
2.0
130.0
253.0
0.0
1.0
155.0
0.0
0.0
0.0
54.0
0.0
2.0
150.0
230.0
0.0
0.0
130.0
0.0
0.0
0.0
54.0
0.0
2.0
160.0
312.0
0.0
0.0
130.0
0.0
0.0
0.0
54.0
1.0
1.0
120.0
171.0
0.0
0.0
137.0
0.0
2.0
0.0
54.0
1.0
2.0
110.0
208.0
0.0
0.0
142.0
0.0
0.0
0.0
54.0
1.0
2.0
120.0
238.0
0.0
0.0
154.0
0.0
0.0
0.0
54.0
1.0
2.0
120.0
246.0
0.0
0.0
110.0
0.0
0.0
0.0
54.0
1.0
2.0
160.0
195.0
0.0
1.0
130.0
0.0
1.0
0.0
54.0
1.0
2.0
160.0
305.0
0.0
0.0
175.0
0.0
0.0
0.0
54.0
1.0
3.0
120.0
217.0
0.0
0.0
137.0
0.0
0.0
0.0
54.0
1.0
3.0
150.0
274.9475365380023
0.0
0.0
122.0
0.0
0.0
0.0
54.0
1.0
4.0
150.0
365.0
0.0
1.0
134.0
0.0
1.0
0.0
55.0
0.0
2.0
110.0
344.0
0.0
1.0
160.0
0.0
0.0
0.0
55.0
0.0
2.0
122.0
320.0
0.0
0.0
155.0
0.0
0.0
0.0
55.0
0.0
2.0
130.0
394.0
0.0
2.0
150.0
0.0
0.0
0.0
55.0
1.0
2.0
120.0
256.0
1.0
0.0
137.0
0.0
0.0
0.0
55.0
1.0
2.0
140.0
196.0
0.0
0.0
150.0
0.0
0.0
0.0
55.0
1.0
2.0
145.0
326.0
0.0
0.0
155.0
0.0
0.0
0.0
55.0
1.0
3.0
110.0
277.0
0.0
0.0
160.0
0.0
0.0
0.0
55.0
1.0
3.0
120.0
220.0
0.0
2.0
134.0
0.0
0.0
0.0
55.0
1.0
4.0
120.0
270.0
0.0
0.0
140.0
0.0
0.0
0.0
55.0
1.0
4.0
140.0
229.0
0.0
0.0
110.0
1.0
0.5
0.0
56.0
1.0
2.0
130.0
184.0
0.0
0.0
100.0
0.0
0.0
0.0
56.0
1.0
3.0
130.0
195.05197292097208
0.0
0.0
114.0
0.0
0.0
0.0
56.0
1.0
3.0
130.0
276.0
0.0
0.0
128.0
1.0
1.0
0.0
56.0
1.0
4.0
120.0
85.0
0.0
0.0
140.0
0.0
0.0
0.0
57.0
0.0
1.0
130.0
308.0
0.0
0.0
98.0
0.0
1.0
0.0
57.0
0.0
4.0
180.0
347.0
0.0
1.0
126.0
1.0
0.8
0.0
57.0
1.0
2.0
140.0
260.0
1.0
0.0
140.0
0.0
0.0
0.0
58.0
1.0
2.0
130.0
230.0
0.0
0.0
150.0
0.0
0.0
0.0
58.0
1.0
2.0
130.0
251.0
0.0
0.0
110.0
0.0
0.0
0.0
58.0
1.0
3.0
140.0
179.0
0.0
0.0
160.0
0.0
0.0
0.0
58.0
1.0
4.0
135.0
222.0
0.0
0.0
100.0
0.0
0.0
0.0
59.0
0.0
2.0
130.0
188.0
0.0
0.0
124.0
0.0
1.0
0.0
59.0
1.0
2.0
140.0
287.0
0.0
0.0
150.0
0.0
0.0
0.0
59.0
1.0
3.0
130.0
318.0
0.0
0.0
120.0
1.0
1.0
0.0
59.0
1.0
3.0
180.0
213.0
0.0
0.0
100.0
0.0
0.0
0.0
59.0
1.0
4.0
140.0
289.6535223918356
0.0
0.0
140.0
0.0
0.0
0.0
60.0
1.0
3.0
120.0
246.0
0.0
2.0
135.0
0.0
0.0
0.0
61.0
0.0
4.0
130.0
294.0
0.0
1.0
120.0
1.0
1.0
0.0
61.0
1.0
4.0
125.0
292.0
0.0
1.0
115.0
1.0
0.0
0.0
62.0
0.0
1.0
160.0
193.0
0.0
0.0
116.0
0.0
0.0
0.0
62.0
1.0
2.0
140.0
271.0
0.0
0.0
152.0
0.0
1.0
0.0
31.0
1.0
4.0
120.0
270.0
0.0
0.0
153.0
1.0
1.5
1.0
33.0
0.0
4.0
100.0
246.0
0.0
0.0
150.0
1.0
1.0
1.0
34.0
1.0
1.0
140.0
156.0
0.0
0.0
180.0
0.0
0.0
1.0
35.0
1.0
2.0
110.0
257.0
0.0
0.0
140.0
0.0
0.0
1.0
36.0
1.0
2.0
120.0
267.0
0.0
0.0
160.0
0.0
3.0
1.0
37.0
1.0
4.0
140.0
207.0
0.0
0.0
130.0
1.0
1.5
1.0
38.0
1.0
4.0
110.0
196.0
0.0
0.0
166.0
0.0
0.0
1.0
38.0
1.0
4.0
120.0
282.0
0.0
0.0
170.0
0.0
0.0
1.0
38.0
1.0
4.0
92.0
117.0
0.0
0.0
134.0
1.0
2.5
1.0
41.0
1.0
4.0
110.0
289.0
0.0
0.0
170.0
0.0
0.0
1.0
43.0
1.0
4.0
150.0
247.0
0.0
0.0
130.0
1.0
2.0
1.0
46.0
1.0
4.0
110.0
202.0
0.0
0.0
150.0
1.0
0.0
1.0
46.0
1.0
4.0
118.0
186.0
0.0
0.0
124.0
0.0
0.0
1.0
46.0
1.0
4.0
120.0
277.0
0.0
0.0
125.0
1.0
1.0
1.0
47.0
1.0
3.0
140.0
193.0
0.0
0.0
145.0
1.0
1.0
1.0
47.0
1.0
4.0
150.0
226.0
0.0
0.0
98.0
1.0
1.5
1.0
48.0
1.0
4.0
106.0
263.0
1.0
0.0
110.0
0.0
0.0
1.0
48.0
1.0
4.0
120.0
260.0
0.0
0.0
115.0
0.0
2.0
1.0
48.0
1.0
4.0
160.0
268.0
0.0
0.0
103.0
1.0
1.0
1.0
49.0
0.0
3.0
160.0
180.0
0.0
0.0
156.0
0.0
1.0
1.0
49.0
1.0
3.0
115.0
265.0
0.0
0.0
175.0
0.0
0.0
1.0
49.0
1.0
4.0
130.0
206.0
0.0
0.0
170.0
0.0
0.0
1.0
50.0
0.0
3.0
140.0
288.0
0.0
0.0
140.0
1.0
0.0
1.0
50.0
1.0
4.0
145.0
264.0
0.0
0.0
150.0
0.0
0.0
1.0
51.0
0.0
4.0
160.0
303.0
0.0
0.0
150.0
1.0
1.0
1.0
52.0
1.0
4.0
130.0
225.0
0.0
0.0
120.0
1.0
2.0
1.0
54.0
1.0
4.0
125.0
216.0
0.0
0.0
140.0
0.0
0.0
1.0
54.0
1.0
4.0
125.0
224.0
0.0
0.0
122.0
0.0
2.0
1.0
55.0
1.0
4.0
140.0
201.0
0.0
0.0
130.0
1.0
3.0
1.0
57.0
1.0
2.0
140.0
265.0
0.0
1.0
145.0
1.0
1.0
1.0
58.0
1.0
3.0
130.0
213.0
0.0
1.0
140.0
0.0
0.0
1.0
59.0
0.0
4.0
130.0
338.0
1.0
1.0
130.0
1.0
1.5
1.0
60.0
1.0
4.0
100.0
248.0
0.0
0.0
125.0
0.0
1.0
1.0
63.0
1.0
4.0
150.0
223.0
0.0
0.0
115.0
0.0
0.0
1.0
65.0
1.0
4.0
140.0
306.0
1.0
0.0
87.0
1.0
1.5
1.0
32.0
1.0
4.0
118.0
529.0
0.0
0.0
130.0
0.0
0.0
1.0
38.0
1.0
4.0
110.0
250.62745608334615
0.0
0.0
150.0
1.0
1.0
1.0
39.0
1.0
4.0
110.0
280.0
0.0
0.0
150.0
0.0
0.0
1.0
40.0
0.0
4.0
150.0
392.0
0.0
0.0
130.0
0.0
2.0
1.0
43.0
1.0
1.0
120.0
291.0
0.0
1.0
155.0
0.0
0.0
1.0
45.0
1.0
4.0
130.0
219.0
0.0
1.0
130.0
1.0
1.0
1.0
46.0
1.0
4.0
120.0
231.0
0.0
0.0
115.0
1.0
0.0
1.0
46.0
1.0
4.0
130.0
222.0
0.0
0.0
112.0
0.0
0.0
1.0
48.0
1.0
4.0
122.0
275.0
1.0
1.0
150.0
1.0
2.0
1.0
48.0
1.0
4.0
160.0
193.0
0.0
0.0
102.0
1.0
3.0
1.0
48.0
1.0
4.0
160.0
329.0
0.0
0.0
92.0
1.0
1.5
1.0
48.0
1.0
4.0
160.0
355.0
0.0
0.0
99.0
1.0
2.0
1.0
50.0
1.0
4.0
130.0
233.0
0.0
0.0
121.0
1.0
2.0
1.0
52.0
1.0
4.0
120.0
182.0
0.0
0.0
150.0
0.0
0.0
1.0
52.0
1.0
4.0
170.0
289.09796300725105
0.0
0.0
126.0
1.0
1.5
1.0
53.0
1.0
4.0
120.0
246.0
0.0
0.0
116.0
1.0
0.0
1.0
54.0
1.0
3.0
120.0
237.0
0.0
0.0
150.0
1.0
1.5
1.0
54.0
1.0
4.0
130.0
242.0
0.0
0.0
91.0
1.0
1.0
1.0
54.0
1.0
4.0
130.0
603.0
1.0
0.0
125.0
1.0
1.0
1.0
54.0
1.0
4.0
140.0
303.36776765715786
0.0
0.0
118.0
1.0
0.0
1.0
54.0
1.0
4.0
200.0
198.0
0.0
0.0
142.0
1.0
2.0
1.0
55.0
1.0
4.0
140.0
268.0
0.0
0.0
128.0
1.0
1.5
1.0
56.0
1.0
4.0
150.0
213.0
1.0
0.0
125.0
1.0
1.0
1.0
57.0
1.0
4.0
150.0
255.0
0.0
0.0
92.0
1.0
3.0
1.0
58.0
1.0
3.0
160.0
211.0
1.0
1.0
92.0
0.0
0.0
1.0
58.0
1.0
4.0
130.0
263.0
0.0
0.0
140.0
1.0
2.0
1.0
41.0
1.0
4.0
130.0
172.0
0.0
1.0
130.0
0.0
2.0
1.0
43.0
1.0
4.0
120.0
175.0
0.0
0.0
120.0
1.0
1.0
1.0
44.0
1.0
2.0
150.0
288.0
0.0
0.0
150.0
1.0
3.0
1.0
44.0
1.0
4.0
130.0
290.0
0.0
0.0
100.0
1.0
2.0
1.0
46.0
1.0
1.0
140.0
272.0
1.0
0.0
175.0
0.0
2.0
1.0
47.0
0.0
3.0
135.0
248.0
1.0
0.0
170.0
0.0
0.0
1.0
48.0
0.0
4.0
138.0
214.0
0.0
0.0
108.0
1.0
1.5
1.0
49.0
1.0
4.0
130.0
341.0
0.0
0.0
120.0
1.0
1.0
1.0
49.0
1.0
4.0
140.0
234.0
0.0
0.0
140.0
1.0
1.0
1.0
51.0
1.0
3.0
135.0
160.0
0.0
0.0
150.0
0.0
2.0
1.0
52.0
1.0
4.0
112.0
342.0
0.0
1.0
96.0
1.0
1.0
1.0
52.0
1.0
4.0
130.0
298.0
0.0
0.0
110.0
1.0
1.0
1.0
52.0
1.0
4.0
140.0
404.0
0.0
0.0
124.0
1.0
2.0
1.0
52.0
1.0
4.0
160.0
246.0
0.0
1.0
82.0
1.0
4.0
1.0
53.0
1.0
3.0
145.0
518.0
0.0
0.0
130.0
0.0
0.0
1.0
53.0
1.0
4.0
180.0
285.0
0.0
1.0
120.0
1.0
1.5
1.0
54.0
1.0
4.0
140.0
216.0
0.0
0.0
105.0
0.0
1.5
1.0
55.0
1.0
2.0
160.0
292.0
1.0
0.0
143.0
1.0
2.0
1.0
55.0
1.0
4.0
145.0
248.0
0.0
0.0
96.0
1.0
2.0
1.0
56.0
0.0
2.0
120.0
279.0
0.0
0.0
150.0
0.0
1.0
1.0
56.0
1.0
4.0
150.0
230.0
0.0
1.0
124.0
1.0
1.5
1.0
56.0
1.0
4.0
170.0
388.0
0.0
1.0
122.0
1.0
2.0
1.0
58.0
1.0
2.0
136.0
164.0
0.0
1.0
99.0
1.0
2.0
1.0
59.0
1.0
4.0
130.0
201.78407370359162
0.0
0.0
125.0
0.0
0.0
1.0
59.0
1.0
4.0
140.0
264.0
1.0
2.0
119.0
1.0
0.0
1.0
65.0
1.0
4.0
170.0
263.0
1.0
0.0
112.0
1.0
2.0
1.0
66.0
1.0
4.0
140.0
256.16652329684064
0.0
0.0
94.0
1.0
1.0
1.0
41.0
1.0
4.0
120.0
336.0
0.0
0.0
118.0
1.0
3.0
1.0
43.0
1.0
4.0
140.0
288.0
0.0
0.0
135.0
1.0
2.0
1.0
44.0
1.0
4.0
135.0
491.0
0.0
0.0
135.0
0.0
0.0
1.0
47.0
0.0
4.0
120.0
205.0
0.0
0.0
98.0
1.0
2.0
1.0
47.0
1.0
4.0
160.0
291.0
0.0
1.0
158.0
1.0
3.0
1.0
49.0
1.0
4.0
128.0
212.0
0.0
0.0
96.0
1.0
0.0
1.0
49.0
1.0
4.0
150.0
222.0
0.0
0.0
122.0
0.0
2.0
1.0
50.0
1.0
4.0
140.0
231.0
0.0
1.0
140.0
1.0
5.0
1.0
50.0
1.0
4.0
140.0
341.0
0.0
1.0
125.0
1.0
2.5
1.0
52.0
1.0
4.0
140.0
266.0
0.0
0.0
134.0
1.0
2.0
1.0
52.0
1.0
4.0
160.0
331.0
0.0
0.0
94.0
1.0
2.5
1.0
54.0
0.0
3.0
130.0
294.0
0.0
1.0
100.0
1.0
0.0
1.0
56.0
1.0
4.0
155.0
342.0
1.0
0.0
150.0
1.0
3.0
1.0
58.0
0.0
2.0
180.0
393.0
0.0
0.0
110.0
1.0
1.0
1.0
65.0
1.0
4.0
130.0
275.0
0.0
1.0
115.0
1.0
1.0
1.0