In [22]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("data/heartdisease/data_cleaned_up.csv")
df

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  num
0     28    1   2       130   132    0        2      185      0      0.0    0
1     29    1   2       120   243    0        0      160      0      0.0    0
2     30    0   1       170   237    0        1      170      0      0.0    0
3     31    0   2       100   219    0        1      150      0      0.0    0
4     32    0   2       105   198    0        0      165      0      0.0    0
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...  ...
255   52    1   4       160   331    0        0       94      1      2.5    1
256   54    0   3       130   294    0        1      100      1      0.0    1
257   56    1   4       155   342    1        0      150      1      3.0    1
258   58    0   2       180   393    0        0      110      1      1.0    1
259   65    1   4       130   275    0        1      115      1      1.0    1

[260 rows x 11 columns]

In [3]:
df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,num
count,260.000000,260.000000,260.000000,260.000000,260.000000,260.000000,260.000000,260.000000,260.000000,260.000000,260.000000
mean,47.792308,0.734615,3.003846,132.688462,248.903846,0.073077,0.226923,139.176923,0.315385,0.608846,0.376923
std,7.849153,0.442389,0.972590,17.726555,65.781861,0.260765,0.471634,23.789932,0.465565,0.932075,0.485550
min,28.000000,0.000000,1.000000,92.000000,85.000000,0.000000,0.000000,82.000000,0.000000,0.000000,0.000000
25%,42.000000,0.000000,2.000000,120.000000,207.750000,0.000000,0.000000,122.000000,0.000000,0.000000,0.000000
50%,49.000000,1.000000,3.000000,130.000000,242.500000,0.000000,0.000000,140.000000,0.000000,0.000000,0.000000
75%,54.000000,1.000000,4.000000,140.000000,280.000000,0.000000,0.000000,155.000000,1.000000,1.000000,1.000000
max,65.000000,1.000000,4.000000,200.000000,603.000000,1.000000,2.000000,190.000000,1.000000,5.000000,1.000000

In [7]:
ok = df[df["num"]==0]
ok.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,num
count,162.000000,162.000000,162.000000,162.000000,162.000000,162.000000,162.000000,162.000000,162.000000,162.000000,162.0
mean,46.827160,0.648148,2.623457,130.672840,237.808642,0.037037,0.234568,145.530864,0.111111,0.196296,0.0
std,8.027577,0.479029,0.884760,16.763177,54.034557,0.189438,0.492720,22.013314,0.315244,0.500917,0.0
min,28.000000,0.000000,1.000000,98.000000,85.000000,0.000000,0.000000,90.000000,0.000000,0.000000,0.0
25%,41.000000,0.000000,2.000000,120.000000,200.250000,0.000000,0.000000,132.500000,0.000000,0.000000,0.0
50%,48.000000,1.000000,2.000000,130.000000,230.000000,0.000000,0.000000,145.000000,0.000000,0.000000,0.0
75%,54.000000,1.000000,3.000000,140.000000,273.000000,0.000000,0.000000,160.000000,0.000000,0.000000,0.0
max,62.000000,1.000000,4.000000,190.000000,412.000000,1.000000,2.000000,190.000000,1.000000,3.000000,0.0

In [5]:
ko = df[df["num"]==1]
ko.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,num
count,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.0
mean,49.387755,0.877551,3.632653,136.020408,267.244898,0.132653,0.214286,128.673469,0.653061,1.290816,1.0
std,7.308564,0.329489,0.765059,18.831307,78.502224,0.340943,0.436717,22.977701,0.478443,1.071956,0.0
min,31.000000,0.000000,1.000000,92.000000,117.000000,0.000000,0.000000,82.000000,0.000000,0.000000,1.0
25%,46.000000,1.000000,4.000000,120.000000,216.750000,0.000000,0.000000,112.750000,0.000000,0.000000,1.0
50%,49.500000,1.000000,4.000000,135.000000,261.500000,0.000000,0.000000,129.000000,1.000000,1.250000,1.0
75%,54.000000,1.000000,4.000000,150.000000,289.750000,0.000000,0.000000,148.750000,1.000000,2.000000,1.0
max,65.000000,1.000000,4.000000,200.000000,603.000000,1.000000,2.000000,180.000000,1.000000,5.000000,1.0

In [13]:
age50 = df[df["age"] == 50].iloc[0]
age50

age          50.0
sex           0.0
cp            2.0
trestbps    110.0
chol        202.0
fbs           0.0
restecg       0.0
thalach     145.0
exang         0.0
oldpeak       0.0
num           0.0
Name: 91, dtype: float64

In [17]:
filter = df["age"] == 50
list(filter)
df[filter]

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  num
91    50    0   2       110   202    0        0      145      0      0.0    0
92    50    0   4       120   328    0        0      110      1      1.0    0
93    50    1   2       120   168    0        0      160      0      0.0    0
94    50    1   2       140   216    0        0      170      0      0.0    0
95    50    1   2       170   209    0        1      116      0      0.0    0
96    50    1   4       140   129    0        0      135      0      0.0    0
97    50    1   4       150   215    0        0      140      1      0.0    0
184   50    0   3       140   288    0        0      140      1      0.0    1
185   50    1   4       145   264    0        0      150      0      0.0    1
208   50    1   4       130   233    0        0      121      1      2.0    1
252   50    1   4       140   231    0        1      140      1      5.0    1
253   50    1   4       140   341    0        1      125      1      2.5    1

In [20]:
df["age"] = df["age"] + 1

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  num
0     30    1   2       130   132    0        2      185      0      0.0    0
1     31    1   2       120   243    0        0      160      0      0.0    0
2     32    0   1       170   237    0        1      170      0      0.0    0
3     33    0   2       100   219    0        1      150      0      0.0    0
4     34    0   2       105   198    0        0      165      0      0.0    0
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...  ...
255   54    1   4       160   331    0        0       94      1      2.5    1
256   56    0   3       130   294    0        1      100      1      0.0    1
257   58    1   4       155   342    1        0      150      1      3.0    1
258   60    0   2       180   393    0        0      110      1      1.0    1
259   67    1   4       130   275    0        1      115      1      1.0    1

[260 rows x 11 columns]

In [23]:
df["age"].apply(np.cos)

0      0.154251
1      0.914742
2      0.834223
3     -0.013277
4     -0.848570
         ...
255   -0.829310
256    0.853220
257    0.119180
258   -0.952413
259   -0.517770
Name: age, Length: 260, dtype: float64

In [28]:
def my_function(x: float):
    if x < 50:
        return x * 2 + 1 - x / 2
    else:
        return x * 2 + 1 - x * 2

In [27]:
df["age"].apply(my_function)
df["age"].apply(lambda x: my_function(x))

0       46.0
1       47.5
2       49.0
3       50.5
4       52.0
       ...
255     82.0
256     85.0
257     88.0
258     91.0
259    101.5
Name: age, Length: 260, dtype: float64

In [29]:
df["age"].apply(lambda x: x * 2 + 1 - x / 2 if x < 50 else x ** 2)

0        46.0
1        47.5
2        49.0
3        50.5
4        52.0
        ...
255    2916.0
256    3136.0
257    3364.0
258    3600.0
259    4489.0
Name: age, Length: 260, dtype: float64