In [1]:
import pandas as pd
import numpy as np

In [2]:
depts = pd.read_csv("data/communes/dept.csv", index_col="id")
depts.head(10)

   num             name  region_id                 region_name
id
80  80            Somme         32             Hauts-de-France
81  81             Tarn         76                   Occitanie
82  82  Tarn-et-Garonne         76                   Occitanie
83  83              Var         93  Provence-Alpes-Côte d'Azur
84  84         Vaucluse         93  Provence-Alpes-Côte d'Azur
85  85           Vendée         52            Pays de la Loire
86  86           Vienne         75          Nouvelle-Aquitaine
87  87     Haute-Vienne         75          Nouvelle-Aquitaine
88  88           Vosges         44                   Grand Est
89  89            Yonne         27     Bourgogne-Franche-Comté

In [3]:
communes = pd.read_csv("data/communes/communes.csv", low_memory=False, index_col="id")
communes.head(10)

,code,nom,nom_norm,lon,lat,epci_id,epci_nom,bassin_vie_id,bassin_vie_nom,zone_emploi_id,...,dept_id,date,type,parent,date_debut,date_fin,old_type,old_nom,old_nom_norm,old_date_fin
id,,,,,,,,,,,,,,,,,,,,,
2439,02439,Les Septvallons,LES SEPTVALLONS,3.674626,49.352746,240200501.0,Communauté de communes du Val de l'Aisne,51250,Fismes,3221.0,...,2,2025-06-26 23:12:22.934702,NaN,NaN,2016-01-01,NaN,COM,Longueval-Barbonval,LONGUEVAL BARBONVAL,2016-01-01
2319,02319,Fonsomme,FONSOMME,3.396855,49.901644,200071892.0,Communauté d'agglomération du Saint-Quentinois,02691,Saint-Quentin,3220.0,...,2,2025-06-26 23:12:10.400503,NaN,NaN,2011-03-25,NaN,COM,Fonsommes,FONSOMMES,2011-03-25
2818,02818,Villiers-Saint-Denis,VILLIERS SAINT DENIS,3.261168,48.997442,240200584.0,Communauté de communes du Canton de Charly-sur...,02163,Charly-sur-Marne,3209.0,...,2,2025-06-26 23:12:07.373128,NaN,NaN,1970-04-13,NaN,COM,Villiers-sur-Marne,VILLIERS SUR MARNE,1970-04-13
1426,01426,Val-Revermont,VAL REVERMONT,5.363443,46.285725,200071751.0,Communauté d'agglomération du Bassin de Bourg-...,01072,Ceyzériat,8405.0,...,1,2025-06-26 23:12:14.270435,NaN,NaN,2016-01-01,NaN,COM,Treffort-Cuisiat,TREFFORT CUISIAT,2016-01-01
2220,02220,Coulonges-Cohan,COULONGES COHAN,3.627456,49.198618,200072031.0,Communauté d'agglomération de la Région de Châ...,02305,Fère-en-Tardenois,3209.0,...,2,2025-06-26 23:12:10.399502,NaN,NaN,1971-01-01,NaN,COM,Coulonges-en-Tardenois,COULONGES EN TARDENOIS,1971-01-01
1097,01097,Chavornay,CHAVORNAY,5.735433,45.916299,200040350.0,Communauté de communes Bugey Sud,01034,Belley,8404.0,...,1,2025-07-09 13:55:56.616733,COM,1453.0,1943-01-01,2019-01-01,NaN,NaN,NaN,NaN
1145,01145,Dompierre-sur-Veyle,DOMPIERRE SUR VEYLE,5.216348,46.067061,200071751.0,Communauté d'agglomération du Bassin de Bourg-...,01053,Bourg-en-Bresse,8405.0,...,1,2025-06-26 23:12:07.316225,NaN,NaN,1954-09-11,NaN,COM,Dompierre,DOMPIERRE,1954-09-11
1215,01215,Surjoux-Lhopital,SURJOUX LHOPITAL,5.783268,46.027653,240100891.0,Communauté de communes du Pays Bellegardien (C...,74269,Seyssel,8416.0,...,1,2025-06-26 23:13:04.695426,NaN,NaN,2019-01-01,NaN,COM,Lhôpital,LHOPITAL,2019-01-01
1266,01266,Montrevel-en-Bresse,MONTREVEL EN BRESSE,5.112513,46.324970,200071751.0,Communauté d'agglomération du Bassin de Bourg-...,01266,Montrevel-en-Bresse,8405.0,...,1,2025-06-26 23:12:04.368255,NaN,NaN,1955-01-29,NaN,COM,Montrevel,MONTREVEL,1955-01-29
1370,01370,Saint-Laurent-sur-Saône,SAINT LAURENT SUR SAONE,4.840157,46.305955,200070308.0,Communauté d'agglomération Mâconnais Beaujolai...,71270,Mâcon,59.0,...,1,2025-06-26 23:12:19.972519,NaN,NaN,1958-12-19,NaN,COM,Saint-Laurent,SAINT LAURENT,1958-12-19

In [5]:
depts["dept_id"] = depts.index
communes_depts = communes.join(depts, on="dept_id", rsuffix="_dept")
communes_depts.head(10)

,code,nom,nom_norm,lon,lat,epci_id,epci_nom,bassin_vie_id,bassin_vie_nom,zone_emploi_id,...,date_fin,old_type,old_nom,old_nom_norm,old_date_fin,num,name,region_id,region_name,dept_id_dept
id,,,,,,,,,,,,,,,,,,,,,
2439,02439,Les Septvallons,LES SEPTVALLONS,3.674626,49.352746,240200501.0,Communauté de communes du Val de l'Aisne,51250,Fismes,3221.0,...,NaN,COM,Longueval-Barbonval,LONGUEVAL BARBONVAL,2016-01-01,02,Aisne,32,Hauts-de-France,2
2319,02319,Fonsomme,FONSOMME,3.396855,49.901644,200071892.0,Communauté d'agglomération du Saint-Quentinois,02691,Saint-Quentin,3220.0,...,NaN,COM,Fonsommes,FONSOMMES,2011-03-25,02,Aisne,32,Hauts-de-France,2
2818,02818,Villiers-Saint-Denis,VILLIERS SAINT DENIS,3.261168,48.997442,240200584.0,Communauté de communes du Canton de Charly-sur...,02163,Charly-sur-Marne,3209.0,...,NaN,COM,Villiers-sur-Marne,VILLIERS SUR MARNE,1970-04-13,02,Aisne,32,Hauts-de-France,2
1426,01426,Val-Revermont,VAL REVERMONT,5.363443,46.285725,200071751.0,Communauté d'agglomération du Bassin de Bourg-...,01072,Ceyzériat,8405.0,...,NaN,COM,Treffort-Cuisiat,TREFFORT CUISIAT,2016-01-01,01,Ain,84,Auvergne-Rhône-Alpes,1
2220,02220,Coulonges-Cohan,COULONGES COHAN,3.627456,49.198618,200072031.0,Communauté d'agglomération de la Région de Châ...,02305,Fère-en-Tardenois,3209.0,...,NaN,COM,Coulonges-en-Tardenois,COULONGES EN TARDENOIS,1971-01-01,02,Aisne,32,Hauts-de-France,2
1097,01097,Chavornay,CHAVORNAY,5.735433,45.916299,200040350.0,Communauté de communes Bugey Sud,01034,Belley,8404.0,...,2019-01-01,NaN,NaN,NaN,NaN,01,Ain,84,Auvergne-Rhône-Alpes,1
1145,01145,Dompierre-sur-Veyle,DOMPIERRE SUR VEYLE,5.216348,46.067061,200071751.0,Communauté d'agglomération du Bassin de Bourg-...,01053,Bourg-en-Bresse,8405.0,...,NaN,COM,Dompierre,DOMPIERRE,1954-09-11,01,Ain,84,Auvergne-Rhône-Alpes,1
1215,01215,Surjoux-Lhopital,SURJOUX LHOPITAL,5.783268,46.027653,240100891.0,Communauté de communes du Pays Bellegardien (C...,74269,Seyssel,8416.0,...,NaN,COM,Lhôpital,LHOPITAL,2019-01-01,01,Ain,84,Auvergne-Rhône-Alpes,1
1266,01266,Montrevel-en-Bresse,MONTREVEL EN BRESSE,5.112513,46.324970,200071751.0,Communauté d'agglomération du Bassin de Bourg-...,01266,Montrevel-en-Bresse,8405.0,...,NaN,COM,Montrevel,MONTREVEL,1955-01-29,01,Ain,84,Auvergne-Rhône-Alpes,1
1370,01370,Saint-Laurent-sur-Saône,SAINT LAURENT SUR SAONE,4.840157,46.305955,200070308.0,Communauté d'agglomération Mâconnais Beaujolai...,71270,Mâcon,59.0,...,NaN,COM,Saint-Laurent,SAINT LAURENT,1958-12-19,01,Ain,84,Auvergne-Rhône-Alpes,1

In [7]:
iris = pd.read_csv("data/communes/iris.csv", low_memory=False, index_col="id")
communes_depts_iris = pd.merge(communes_depts, iris, left_on="id", right_on="commune_id", suffixes=("", "_iris"))
communes_depts_iris.head(10)

,code,nom,nom_norm,lon,lat,epci_id,epci_nom,bassin_vie_id,bassin_vie_nom,zone_emploi_id,...,is_irisee,arrondissement_code,arrondissement_nom,type_iris,grd_quart_code,grd_quart_nom,in_ctu,commune_id,date_iris,is_main
0,02439,Les Septvallons,LES SEPTVALLONS,3.674626,49.352746,240200501.0,Communauté de communes du Val de l'Aisne,51250,Fismes,3221.0,...,f,02439,Les Septvallons,C,0243900,NaN,f,2439,2025-06-26 23:17:49.570077,t
1,02319,Fonsomme,FONSOMME,3.396855,49.901644,200071892.0,Communauté d'agglomération du Saint-Quentinois,02691,Saint-Quentin,3220.0,...,f,02319,Fonsomme,C,0231900,NaN,f,2319,2025-06-26 23:17:38.562785,t
2,02818,Villiers-Saint-Denis,VILLIERS SAINT DENIS,3.261168,48.997442,240200584.0,Communauté de communes du Canton de Charly-sur...,02163,Charly-sur-Marne,3209.0,...,f,02818,Villiers-Saint-Denis,C,0281800,NaN,f,2818,2025-06-26 23:17:35.943746,t
3,01426,Val-Revermont,VAL REVERMONT,5.363443,46.285725,200071751.0,Communauté d'agglomération du Bassin de Bourg-...,01072,Ceyzériat,8405.0,...,f,01426,Val-Revermont,C,0142600,NaN,f,1426,2025-06-26 23:17:42.074674,t
4,02220,Coulonges-Cohan,COULONGES COHAN,3.627456,49.198618,200072031.0,Communauté d'agglomération de la Région de Châ...,02305,Fère-en-Tardenois,3209.0,...,f,02220,Coulonges-Cohan,C,0222000,NaN,f,2220,2025-06-26 23:17:38.561768,t
5,01145,Dompierre-sur-Veyle,DOMPIERRE SUR VEYLE,5.216348,46.067061,200071751.0,Communauté d'agglomération du Bassin de Bourg-...,01053,Bourg-en-Bresse,8405.0,...,f,01145,Dompierre-sur-Veyle,C,0114500,NaN,f,1145,2025-06-26 23:17:35.893816,t
6,01215,Surjoux-Lhopital,SURJOUX LHOPITAL,5.783268,46.027653,240100891.0,Communauté de communes du Pays Bellegardien (C...,74269,Seyssel,8416.0,...,f,01215,Surjoux-Lhopital,C,0121500,NaN,f,1215,2025-06-26 23:18:24.804561,t
7,01266,Montrevel-en-Bresse,MONTREVEL EN BRESSE,5.112513,46.324970,200071751.0,Communauté d'agglomération du Bassin de Bourg-...,01266,Montrevel-en-Bresse,8405.0,...,f,01266,Montrevel-en-Bresse,C,0126600,NaN,f,1266,2025-06-26 23:17:33.470847,t
8,01370,Saint-Laurent-sur-Saône,SAINT LAURENT SUR SAONE,4.840157,46.305955,200070308.0,Communauté d'agglomération Mâconnais Beaujolai...,71270,Mâcon,59.0,...,f,01370,Saint-Laurent-sur-Saône,C,0137000,NaN,f,1370,2025-06-26 23:17:46.767216,t
9,01384,Saint-Rambert-en-Bugey,SAINT RAMBERT EN BUGEY,5.440152,45.950977,240100883.0,Communauté de communes de la Plaine de l'Ain,01004,Ambérieu-en-Bugey,8405.0,...,f,01384,Saint-Rambert-en-Bugey,C,0138400,NaN,f,1384,2025-06-26 23:17:33.015229,t

In [9]:
cps = pd.read_csv("data/communes/cp.csv", low_memory=False)
cps.head(10)

   code_postal code_insee
0         1000      01053
1         1000      01344
2         1090      01165
3         1090      01169
4         1090      01183
5         1090      01225
6         1090      01258
7         1090      01263
8         1100      01011
9         1100      01014

In [11]:
final = pd.merge(communes_depts_iris, cps, left_on="code", right_on="code_insee", suffixes=("", "_iris"))
final

,code,nom,nom_norm,lon,lat,epci_id,epci_nom,bassin_vie_id,bassin_vie_nom,zone_emploi_id,...,arrondissement_nom,type_iris,grd_quart_code,grd_quart_nom,in_ctu,commune_id,date_iris,is_main,code_postal,code_insee
0,02439,Les Septvallons,LES SEPTVALLONS,3.674626,49.352746,240200501.0,Communauté de communes du Val de l'Aisne,51250,Fismes,3221.0,...,Les Septvallons,C,0243900,NaN,f,2439,2025-06-26 23:17:49.570077,t,2160,02439
1,02319,Fonsomme,FONSOMME,3.396855,49.901644,200071892.0,Communauté d'agglomération du Saint-Quentinois,02691,Saint-Quentin,3220.0,...,Fonsomme,C,0231900,NaN,f,2319,2025-06-26 23:17:38.562785,t,2110,02319
2,02818,Villiers-Saint-Denis,VILLIERS SAINT DENIS,3.261168,48.997442,240200584.0,Communauté de communes du Canton de Charly-sur...,02163,Charly-sur-Marne,3209.0,...,Villiers-Saint-Denis,C,0281800,NaN,f,2818,2025-06-26 23:17:35.943746,t,2310,02818
3,01426,Val-Revermont,VAL REVERMONT,5.363443,46.285725,200071751.0,Communauté d'agglomération du Bassin de Bourg-...,01072,Ceyzériat,8405.0,...,Val-Revermont,C,0142600,NaN,f,1426,2025-06-26 23:17:42.074674,t,1370,01426
4,02220,Coulonges-Cohan,COULONGES COHAN,3.627456,49.198618,200072031.0,Communauté d'agglomération de la Région de Châ...,02305,Fère-en-Tardenois,3209.0,...,Coulonges-Cohan,C,0222000,NaN,f,2220,2025-06-26 23:17:38.561768,t,2130,02220
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54190,49183,Val d'Erdre-Auxence,VAL D ERDRE AUXENCE,-0.931389,47.513413,200071868.0,Communauté de communes des Vallées du Haut-Anjou,49054,Candé,5202.0,...,Val d'Erdre-Auxence,C,4918300,NaN,f,49183,2025-06-26 23:17:34.83472,t,49440,49183
54191,51611,Vert-Toulon,VERT TOULON,3.906460,48.847976,200067684.0,"Communauté d''agglomération Épernay,Coteaux et...",51612,Blancs-Coteaux,4406.0,...,Vert-Toulon,C,5161100,NaN,f,51611,2025-06-26 23:17:52.909296,t,51130,51611
54192,60456,La Neuville-Roy,LA NEUVILLE ROY,2.582093,49.479639,246000566.0,Communauté de communes du Plateau Picard,60223,Estrées-Saint-Denis,3210.0,...,La Neuville-Roy,C,6045600,NaN,f,60456,2025-06-26 23:18:10.463528,t,60190,60456
54193,67228,Neugartheim-Ittlenheim,NEUGARTHEIM ITTLENHEIM,7.541469,48.656860,200034635.0,Communauté de communes du Kochersberg,67495,Truchtersheim,4423.0,...,Neugartheim-Ittlenheim,C,6722800,NaN,f,67228,2025-06-26 23:17:59.262384,t,67370,67228
54194,07259,Saint-Just-d'Ardèche,SAINT JUST D ARDECHE,4.624979,44.293723,240700864.0,Communauté de communes du Rhône aux Gorges de ...,30202,Pont-Saint-Esprit,55.0,...,Saint-Just-d'Ardèche,C,0725900,NaN,f,7259,2025-06-26 23:17:49.646489,t,7700,07259

In [12]:
cp = 38250
result = final[final["code_postal"] == cp]
result

,code,nom,nom_norm,lon,lat,epci_id,epci_nom,bassin_vie_id,bassin_vie_nom,zone_emploi_id,...,arrondissement_nom,type_iris,grd_quart_code,grd_quart_nom,in_ctu,commune_id,date_iris,is_main,code_postal,code_insee
1815,38205,Lans-en-Vercors,LANS EN VERCORS,5.590175,45.120966,243801024.0,Communauté de communes du Massif du Vercors,38548,Villard-de-Lans,8409.0,...,Lans-en-Vercors,C,3820500,NaN,f,38205,2025-06-26 23:17:50.305395,t,38250,38205
23712,38433,Saint-Nizier-du-Moucherotte,SAINT NIZIER DU MOUCHEROTTE,5.631374,45.164846,243801024.0,Communauté de communes du Massif du Vercors,38185,Grenoble,8409.0,...,Saint-Nizier-du-Moucherotte,C,3843300,NaN,f,38433,2025-06-26 23:18:18.892102,t,38250,38433
23823,38548,Villard-de-Lans,VILLARD DE LANS,5.543917,45.060117,243801024.0,Communauté de communes du Massif du Vercors,38548,Villard-de-Lans,8409.0,...,Villard-de-Lans,C,3854800,NaN,f,38548,2025-06-26 23:18:14.343071,t,38250,38548
53789,38129,Corrençon-en-Vercors,CORRENCON EN VERCORS,5.517578,45.011709,243801024.0,Communauté de communes du Massif du Vercors,38548,Villard-de-Lans,8409.0,...,Corrençon-en-Vercors,C,3812900,NaN,f,38129,2025-06-26 23:17:58.185421,t,38250,38129

In [13]:
result.to_csv("data/communes/result.csv", index=False)